mapping = {
    "Left mouse button": {"alias": "VK_LBUTTON", "virtual_key": "0x01"},
    "Right mouse button": {"alias": "VK_RBUTTON", "virtual_key": "0x02"},
    "Control-break processing": {"alias": "VK_CANCEL", "virtual_key": "0x03"},
    "Middle mouse button (three-button mouse)": {
        "alias": "VK_MBUTTON",
        "virtual_key": "0x04",
    },
    "X1 mouse button": {"alias": "VK_XBUTTON1", "virtual_key": "0x05"},
    "X2 mouse button": {"alias": "VK_XBUTTON2", "virtual_key": "0x06"},
    "Undefined": {"alias": "-", "virtual_key": "0x3A-40"},
    "BACKSPACE": {"alias": "VK_BACK", "virtual_key": "0x08"},
    "TAB": {"alias": "VK_TAB", "virtual_key": "0x09"},
    "Reserved": {"alias": "VK_NONAME", "virtual_key": "0xFC"},
    "CLEAR": {"alias": "VK_CLEAR", "virtual_key": "0x0C"},
    "ENTER": {"alias": "VK_RETURN", "virtual_key": "0x0D"},
    "SHIFT": {"alias": "VK_SHIFT", "virtual_key": "0x10"},
    "CTRL": {"alias": "VK_CONTROL", "virtual_key": "0x11"},
    "ALT": {"alias": "VK_MENU", "virtual_key": "0x12"},
    "PAUSE": {"alias": "VK_PAUSE", "virtual_key": "0x13"},
    "CAPS LOCK": {"alias": "VK_CAPITAL", "virtual_key": "0x14"},
    "IME Kana mod": {"alias": "VK_KANA", "virtual_key": "0x15"},
    "IME Hanguel mode (maintained for compatibility; use VK_HANGUL)": {
        "alias": "VK_HANGUEL",
        "virtual_key": "0x15",
    },
    "IME Hangul mod": {"alias": "VK_HANGUL", "virtual_key": "0x15"},
    "IME On": {"alias": "VK_IME_ON", "virtual_key": "0x16"},
    "IME Junja mod": {"alias": "VK_JUNJA", "virtual_key": "0x17"},
    "IME final mod": {"alias": "VK_FINAL", "virtual_key": "0x18"},
    "IME Hanja mod": {"alias": "VK_HANJA", "virtual_key": "0x19"},
    "IME Kanji mod": {"alias": "VK_KANJI", "virtual_key": "0x19"},
    "IME Off": {"alias": "VK_IME_OFF", "virtual_key": "0x1A"},
    "ESC": {"alias": "VK_ESCAPE", "virtual_key": "0x1B"},
    "IME convert": {"alias": "VK_CONVERT", "virtual_key": "0x1C"},
    "IME nonconvert": {"alias": "VK_NONCONVERT", "virtual_key": "0x1D"},
    "IME accept": {"alias": "VK_ACCEPT", "virtual_key": "0x1E"},
    "IME mode change request": {"alias": "VK_MODECHANGE", "virtual_key": "0x1F"},
    "SPACEBAR": {"alias": "VK_SPACE", "virtual_key": "0x20"},
    "PAGE UP": {"alias": "VK_PRIOR", "virtual_key": "0x21"},
    "PAGE DOWN": {"alias": "VK_NEXT", "virtual_key": "0x22"},
    "END": {"alias": "VK_END", "virtual_key": "0x23"},
    "HOME": {"alias": "VK_HOME", "virtual_key": "0x24"},
    "LEFT ARROW": {"alias": "VK_LEFT", "virtual_key": "0x25"},
    "UP ARROW": {"alias": "VK_UP", "virtual_key": "0x26"},
    "RIGHT ARROW": {"alias": "VK_RIGHT", "virtual_key": "0x27"},
    "DOWN ARROW": {"alias": "VK_DOWN", "virtual_key": "0x28"},
    "SELECT": {"alias": "VK_SELECT", "virtual_key": "0x29"},
    "PRINT": {"alias": "VK_PRINT", "virtual_key": "0x2A"},
    "EXECUTE": {"alias": "VK_EXECUTE", "virtual_key": "0x2B"},
    "PRINT SCREEN": {"alias": "VK_SNAPSHOT", "virtual_key": "0x2C"},
    "INS": {"alias": "VK_INSERT", "virtual_key": "0x2D"},
    "DEL": {"alias": "VK_DELETE", "virtual_key": "0x2E"},
    "HELP": {"alias": "VK_HELP", "virtual_key": "0x2F"},
    "0": {"alias": "", "virtual_key": "0x30"},
    "1": {"alias": "", "virtual_key": "0x31"},
    "2": {"alias": "", "virtual_key": "0x32"},
    "3": {"alias": "", "virtual_key": "0x33"},
    "4": {"alias": "", "virtual_key": "0x34"},
    "5": {"alias": "", "virtual_key": "0x35"},
    "6": {"alias": "", "virtual_key": "0x36"},
    "7": {"alias": "", "virtual_key": "0x37"},
    "8": {"alias": "", "virtual_key": "0x38"},
    "9": {"alias": "", "virtual_key": "0x39"},
    "A": {"alias": "", "virtual_key": "0x41"},
    "B": {"alias": "", "virtual_key": "0x42"},
    "C": {"alias": "", "virtual_key": "0x43"},
    "D": {"alias": "", "virtual_key": "0x44"},
    "E": {"alias": "", "virtual_key": "0x45"},
    "F": {"alias": "", "virtual_key": "0x46"},
    "G": {"alias": "", "virtual_key": "0x47"},
    "H": {"alias": "", "virtual_key": "0x48"},
    "I": {"alias": "", "virtual_key": "0x49"},
    "J": {"alias": "", "virtual_key": "0x4A"},
    "K": {"alias": "", "virtual_key": "0x4B"},
    "L": {"alias": "", "virtual_key": "0x4C"},
    "M": {"alias": "", "virtual_key": "0x4D"},
    "N": {"alias": "", "virtual_key": "0x4E"},
    "O": {"alias": "", "virtual_key": "0x4F"},
    "P": {"alias": "", "virtual_key": "0x50"},
    "Q": {"alias": "", "virtual_key": "0x51"},
    "R": {"alias": "", "virtual_key": "0x52"},
    "S": {"alias": "", "virtual_key": "0x53"},
    "T": {"alias": "", "virtual_key": "0x54"},
    "U": {"alias": "", "virtual_key": "0x55"},
    "V": {"alias": "", "virtual_key": "0x56"},
    "W": {"alias": "", "virtual_key": "0x57"},
    "X": {"alias": "", "virtual_key": "0x58"},
    "Y": {"alias": "", "virtual_key": "0x59"},
    "Z": {"alias": "", "virtual_key": "0x5A"},
    "Left Windows key (Natural keyboard)": {"alias": "VK_LWIN", "virtual_key": "0x5B"},
    "Right Windows key (Natural keyboard)": {"alias": "VK_RWIN", "virtual_key": "0x5C"},
    "Applications key (Natural keyboard)": {"alias": "VK_APPS", "virtual_key": "0x5D"},
    "Computer Sleep": {"alias": "VK_SLEEP", "virtual_key": "0x5F"},
    "Numeric keypad 0": {"alias": "VK_NUMPAD0", "virtual_key": "0x60"},
    "Numeric keypad 1": {"alias": "VK_NUMPAD1", "virtual_key": "0x61"},
    "Numeric keypad 2": {"alias": "VK_NUMPAD2", "virtual_key": "0x62"},
    "Numeric keypad 3": {"alias": "VK_NUMPAD3", "virtual_key": "0x63"},
    "Numeric keypad 4": {"alias": "VK_NUMPAD4", "virtual_key": "0x64"},
    "Numeric keypad 5": {"alias": "VK_NUMPAD5", "virtual_key": "0x65"},
    "Numeric keypad 6": {"alias": "VK_NUMPAD6", "virtual_key": "0x66"},
    "Numeric keypad 7": {"alias": "VK_NUMPAD7", "virtual_key": "0x67"},
    "Numeric keypad 8": {"alias": "VK_NUMPAD8", "virtual_key": "0x68"},
    "Numeric keypad 9": {"alias": "VK_NUMPAD9", "virtual_key": "0x69"},
    "Multipl": {"alias": "VK_MULTIPLY", "virtual_key": "0x6A"},
    "Add": {"alias": "VK_ADD", "virtual_key": "0x6B"},
    "Separator": {"alias": "VK_SEPARATOR", "virtual_key": "0x6C"},
    "Subtract": {"alias": "VK_SUBTRACT", "virtual_key": "0x6D"},
    "Decimal": {"alias": "VK_DECIMAL", "virtual_key": "0x6E"},
    "Divid": {"alias": "VK_DIVIDE", "virtual_key": "0x6F"},
    "F1": {"alias": "VK_F1", "virtual_key": "0x70"},
    "F2": {"alias": "VK_F2", "virtual_key": "0x71"},
    "F3": {"alias": "VK_F3", "virtual_key": "0x72"},
    "F4": {"alias": "VK_F4", "virtual_key": "0x73"},
    "F5": {"alias": "VK_F5", "virtual_key": "0x74"},
    "F6": {"alias": "VK_F6", "virtual_key": "0x75"},
    "F7": {"alias": "VK_F7", "virtual_key": "0x76"},
    "F8": {"alias": "VK_F8", "virtual_key": "0x77"},
    "F9": {"alias": "VK_F9", "virtual_key": "0x78"},
    "F10": {"alias": "VK_F10", "virtual_key": "0x79"},
    "F11": {"alias": "VK_F11", "virtual_key": "0x7A"},
    "F12": {"alias": "VK_F12", "virtual_key": "0x7B"},
    "F13": {"alias": "VK_F13", "virtual_key": "0x7C"},
    "F14": {"alias": "VK_F14", "virtual_key": "0x7D"},
    "F15": {"alias": "VK_F15", "virtual_key": "0x7E"},
    "F16": {"alias": "VK_F16", "virtual_key": "0x7F"},
    "F17": {"alias": "VK_F17", "virtual_key": "0x80"},
    "F18": {"alias": "VK_F18", "virtual_key": "0x81"},
    "F19": {"alias": "VK_F19", "virtual_key": "0x82"},
    "F20": {"alias": "VK_F20", "virtual_key": "0x83"},
    "F21": {"alias": "VK_F21", "virtual_key": "0x84"},
    "F22": {"alias": "VK_F22", "virtual_key": "0x85"},
    "F23": {"alias": "VK_F23", "virtual_key": "0x86"},
    "F24": {"alias": "VK_F24", "virtual_key": "0x87"},
    "Unassigned": {"alias": "-", "virtual_key": "0xE8"},
    "NUM LOCK": {"alias": "VK_NUMLOCK", "virtual_key": "0x90"},
    "SCROLL LOCK": {"alias": "VK_SCROLL", "virtual_key": "0x91"},
    "OEM specific": {"alias": "", "virtual_key": "0xE9-F5"},
    "Left SHIFT": {"alias": "VK_LSHIFT", "virtual_key": "0xA0"},
    "Right SHIFT": {"alias": "VK_RSHIFT", "virtual_key": "0xA1"},
    "Left CONTROL": {"alias": "VK_LCONTROL", "virtual_key": "0xA2"},
    "Right CONTROL": {"alias": "VK_RCONTROL", "virtual_key": "0xA3"},
    "Left MENU": {"alias": "VK_LMENU", "virtual_key": "0xA4"},
    "Right MENU": {"alias": "VK_RMENU", "virtual_key": "0xA5"},
    "Browser Bac": {"alias": "VK_BROWSER_BACK", "virtual_key": "0xA6"},
    "Browser Forward": {"alias": "VK_BROWSER_FORWARD", "virtual_key": "0xA7"},
    "Browser Refresh": {"alias": "VK_BROWSER_REFRESH", "virtual_key": "0xA8"},
    "Browser Stop": {"alias": "VK_BROWSER_STOP", "virtual_key": "0xA9"},
    "Browser Search": {"alias": "VK_BROWSER_SEARCH", "virtual_key": "0xAA"},
    "Browser Favorites": {"alias": "VK_BROWSER_FAVORITES", "virtual_key": "0xAB"},
    "Browser Start and Hom": {"alias": "VK_BROWSER_HOME", "virtual_key": "0xAC"},
    "Volume Mut": {"alias": "VK_VOLUME_MUTE", "virtual_key": "0xAD"},
    "Volume Down": {"alias": "VK_VOLUME_DOWN", "virtual_key": "0xAE"},
    "Volume Up": {"alias": "VK_VOLUME_UP", "virtual_key": "0xAF"},
    "Next Trac": {"alias": "VK_MEDIA_NEXT_TRACK", "virtual_key": "0xB0"},
    "Previous Trac": {"alias": "VK_MEDIA_PREV_TRACK", "virtual_key": "0xB1"},
    "Stop Media": {"alias": "VK_MEDIA_STOP", "virtual_key": "0xB2"},
    "Play/Pause Media": {"alias": "VK_MEDIA_PLAY_PAUSE", "virtual_key": "0xB3"},
    "Start Mail": {"alias": "VK_LAUNCH_MAIL", "virtual_key": "0xB4"},
    "Select Media": {"alias": "VK_LAUNCH_MEDIA_SELECT", "virtual_key": "0xB5"},
    "Start Application 1": {"alias": "VK_LAUNCH_APP1", "virtual_key": "0xB6"},
    "Start Application 2": {"alias": "VK_LAUNCH_APP2", "virtual_key": "0xB7"},
    ";:": {
        "alias": "VK_OEM_1",
        "virtual_key": "0xBA",
    },
    "+": {"alias": "VK_OEM_PLUS", "virtual_key": "0xBB"},
    ",": {"alias": "VK_OEM_COMMA", "virtual_key": "0xBC"},
    "-": {"alias": "VK_OEM_MINUS", "virtual_key": "0xBD"},
    ".": {
        "alias": "VK_OEM_PERIOD",
        "virtual_key": "0xBE",
    },
    "/?": {
        "alias": "VK_OEM_2",
        "virtual_key": "0xBF",
    },
    "`~": {
        "alias": "VK_OEM_3",
        "virtual_key": "0xC0",
    },
    "[{": {
        "alias": "VK_OEM_4",
        "virtual_key": "0xDB",
    },
    "\\|": {
        "alias": "VK_OEM_5",
        "virtual_key": "0xDC",
    },
    "]}": {
        "alias": "VK_OEM_6",
        "virtual_key": "0xDD",
    },
    "single-quote/double-quote": {
        "alias": "VK_OEM_7",
        "virtual_key": "0xDE",
    },
    "Used for miscellaneous characters; it can vary by keyboard.": {
        "alias": "VK_OEM_8",
        "virtual_key": "0xDF",
    },
    "The <> keys on the US standard keyboard, or the \\\\| key on the non-US 102-key keyboard": {
        "alias": "VK_OEM_102",
        "virtual_key": "0xE2",
    },
    "IME PROCESS": {"alias": "VK_PROCESSKEY", "virtual_key": "0xE5"},
    "Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. For more information, see Remark in KEYBDINPUT, SendInput, WM_KEYDOWN, and WM_KEYUP": {
        "alias": "VK_PACKET",
        "virtual_key": "0xE7",
    },
    "Attn": {"alias": "VK_ATTN", "virtual_key": "0xF6"},
    "CrSel": {"alias": "VK_CRSEL", "virtual_key": "0xF7"},
    "ExSel": {"alias": "VK_EXSEL", "virtual_key": "0xF8"},
    "Erase EOF": {"alias": "VK_EREOF", "virtual_key": "0xF9"},
    "Pla": {"alias": "VK_PLAY", "virtual_key": "0xFA"},
    "Zoom": {"alias": "VK_ZOOM", "virtual_key": "0xFB"},
    "PA1": {"alias": "VK_PA1", "virtual_key": "0xFD"},
    "Clear": {"alias": "VK_OEM_CLEAR", "virtual_key": "0xFE"},
}
